[package]
name = "steamworksjs"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.8.4", features = ["tokio_rt", "napi6", "serde-json"] }
napi-derive = "3.5.3"
lazy_static = "1"
tokio = { version = "1", features = ["sync", "time"] }
steamworks = { git = "https://github.com/Noxime/steamworks-rs/", rev = "185168865bf417a3d0232da92f654ead94a6ea5e", features = ["serde"] }
serde = "1"
serde_json = "1"

[build-dependencies]
napi-build = "2.3.1"

[profile.release]
lto = true
